### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by ghost**
I refactored the complete code so the code is much clearer now and easier to expand with further features.

### CODE REVIEW

**Comment by NienteSpigotSenzaJava** [comment]
Merged. Can I ask the usage of the final keyword in the method's parameters?

**Comment by ghost** [comment]
For example:
 `public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {`

Why would you ever want to change the sender, command, label or the args. Makes no sense so make it final.
 `public boolean onCommand(final CommandSender sender, final Command command, final String label, final String[] args) {`

That it makes no sense to change the method parameters inside of a method applies (nearly?) always.

There are some discussions if you should make every method parameter final or not (for example https://stackoverflow.com/questions/500508/why-should-i-use-the-keyword-final-on-a-method-parameter-in-java). In the end it's just a choose of code style. I think it's better to declare every arg as final but it normaly makes nearly no difference.

**Comment by ghost** [comment]
Btw if you have any other question about the refactored code feel free to ask.

**Comment by NienteSpigotSenzaJava** [comment]
Got it, i'm testing out the plugin and i will make a new release today.

**Comment by NienteSpigotSenzaJava** [comment]
Thank you for your huge contribution!

**Pull request merged**
